### ISSUE TITLE
incompatible version

### ISSUE THREAD

**Issue by gidel14** [Pab450/Vote-Reward-for-developers#2]
hello Developer of VoteReward I have a problem which is stated in the console Could not load plugin 'VoteReward': Incompatible API version (plugin requires one of: 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0. 0-ALPHA10, 3.0.0-ALPHA11) but I have tested the All versions and still the plugin why?

**Comment by Pab450** [comment]
Hello my friend ! I am sorry to announce it but you arrive too late! The plugin has not been updated for new versions of Pocketmine, so you can not use it .. this plugin is not compatible with the new Pocketmine API! In addition this version is a simplified version and made for developers!
